name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank You For Supporting Our Project! Make Sure Your Read Our Code of Conduct! [Code of Conduct](https://github.com/Open-Source-Autonomous-Boat/OSAB/blob/main/CODE_OF_CONDUCT.md)'
        pr-message: 'Thank You For Supporting Our Project! Make Sure Your Read Our Code of Conduct! [Code of Conduct](https://github.com/Open-Source-Autonomous-Boat/OSAB/blob/main/CODE_OF_CONDUCT.md)'
